refactor: unify error message format and refactor related functions ℹ️
- keep `usage` function simple
- use `-s`/`-h` option for optional argument of `die` function
- use bash builtin `type -P` instead of `which` command 🐚
- rename var, use `COLOR_INDEX` instead of `COUNT`

diff --git a/bin/ap b/bin/ap
--- a/bin/ap
+++ b/bin/ap
@@ -19,23 +19,43 @@ readonly PROG_VERSION='2.x-dev'
 # util functions
 ################################################################################
 
-redPrint() {
+errorMsgPrint() {
+  local errorMsg="$PROG: $*"
   # if stdout is a terminal, turn on color output.
   #   '-t' check: is a terminal?
   #   check isatty in bash https://stackoverflow.com/questions/10022323
   if [ -t 1 ]; then
-    printf '\e[1;31m%s\e[0m\n' "$*"
+    printf '\e[1;31m%s\e[0m\n' "$errorMsg"
   else
-    printf '%s\n' "$*"
+    printf '%s\n' "$errorMsg"
   fi
-}
+} >&2
 
 die() {
-  redPrint "Error: $*" >&2
-  exit 1
-}
+  local prompt_help=false exit_status=2
+  while (($# > 0)); do
+    case "$1" in
+    -h)
+      prompt_help=true
+      shift
+      ;;
+    -s)
+      exit_status=$2
+      shift 2
+      ;;
+    *)
+      break
+      ;;
+    esac
+  done
 
-# `realpath` command existed on Linux and macOS, return resolved physical path
+  (($# > 0)) && errorMsgPrint "$*"
+  $prompt_help && echo "Try '$PROG --help' for more information."
+
+  exit "$exit_status"
+} >&2
+
+# `realpath` command exists on Linux and macOS, return resolved physical path
 #   - realpath command on macOS do NOT support option `-e`;
 #     combined `[ -e $file ]` to check file existence first.
 #   - How can I get the behavior of GNU's readlink -f on a Mac?
@@ -45,14 +65,7 @@ realpath() {
 }
 
 usage() {
-  local -r exit_code=${1:-0}
-  (($# > 0)) && shift
-  local -r out=$(((exit_code != 0) + 1))
-
-  # NOTE: $'foo' is the escape sequence syntax of bash
-  (($# > 0)) && redPrint "$*"$'\n' >&"$out"
-
-  cat >&"$out" <<EOF
+  cat <<EOF
 Usage: $PROG [OPTION]... [FILE]...
 convert to Absolute Path.
 
@@ -65,7 +78,7 @@ Options:
   -V, --version   display version information and exit
 EOF
 
-  exit "$exit_code"
+  exit
 }
 
 progVersion() {
@@ -92,7 +105,7 @@ while (($# > 0)); do
     break
     ;;
   -*)
-    usage 2 "$PROG: unrecognized option '$1'"
+    die -h "unrecognized option '$1'"
     ;;
   *)
     # if not option, treat all follow files as args
@@ -113,8 +126,8 @@ has_error=false
 
 for f in "${files[@]}"; do
   realpath "$f" || {
-    redPrint "error: $f does not exists!" >&2
     has_error=true
+    errorMsgPrint "$f: No such file or directory!"
   }
 done
 
