+ uq: add max input defensive check option

diff --git a/bin/uq b/bin/uq
--- a/bin/uq
+++ b/bin/uq
@@ -12,7 +12,7 @@
 # @author Jerry Lee (oldratlee at gmail dot com)
 set -eEuo pipefail
 
-PROG="$(basename "$0")"
+readonly PROG="$(basename "$0")"
 
 ################################################################################
 # util functions
@@ -34,6 +34,27 @@ yellowEcho() {
 die() {
     redEcho "Error: $*" 1>&2
     exit 1
+}
+
+convertHumanReadableSizeToSize() {
+    local human_readable_size="$1"
+
+    [[ "$human_readable_size" =~ ^([0-9][0-9]*)([kmg]?)$ ]] || return 1
+
+    local size="${BASH_REMATCH[1]}" unit="${BASH_REMATCH[2]}"
+    case "$unit" in
+    g)
+        ((size *= 1024 * 1024 * 1024))
+        ;;
+    m)
+        ((size *= 1024 * 1024))
+        ;;
+    k)
+        ((size *= 1024))
+        ;;
+    esac
+
+    echo "$size"
 }
 
 usage() {
@@ -70,8 +91,9 @@ Options:
                           that are not repeated in the input
   -i, --ignore-case     ignore differences in case when comparing
   -z, --zero-terminated line delimiter is NUL, not newline
-
-Miscellaneous:
+  -XM, --max-input      max input size(count by char), support k,m,g postfix
+                          default is 256m
+                          avoid consuming large memory unexpectedly
   -h, --help            display this help and exit
 EOF
 
@@ -89,6 +111,7 @@ uq_opt_repeated_method=none
 uq_opt_only_unique=0
 uq_opt_ignore_case=0
 uq_opt_zero_terminated=0
+uq_max_input_human_readable_size=256m
 declare -a argv=()
 
 while (($# > 0)); do
@@ -107,9 +130,11 @@ while (($# > 0)); do
         ;;
     --all-repeated=*)
         uq_opt_all_repeated=1
+
         uq_opt_repeated_method=$(echo "$1" | awk -F= '{print $2}')
         [[ $uq_opt_repeated_method == 'none' || $uq_opt_repeated_method == 'prepend' || $uq_opt_repeated_method == 'separate' ]] ||
             usage 1 "$PROG: invalid argument ‘${uq_opt_repeated_method}’ for ‘--all-repeated’${nl}Valid arguments are:$nl  - ‘none’$nl  - ‘prepend’$nl  - ‘separate’"
+
         shift
         ;;
     -u | --unique)
@@ -123,6 +148,10 @@ while (($# > 0)); do
     -z | --zero-terminated)
         uq_opt_zero_terminated=1
         shift
+        ;;
+    -XM | --max-input)
+        uq_max_input_human_readable_size="$2"
+        shift 2
         ;;
     -h | --help)
         usage
@@ -153,6 +182,9 @@ done
 
 [[ $uq_opt_all_repeated == 1 && $uq_opt_repeated_method == none && ($uq_opt_count == 0 && $uq_opt_only_repeated == 0) ]] &&
     yellowEcho "[$PROG] WARN: -D/--all-repeated=none option without -c/-d option, just cat input simply!" >&2
+
+uq_max_input_size="$(convertHumanReadableSizeToSize "$uq_max_input_human_readable_size")" ||
+    usage 2 "[$PROG] ERROR: illegal value of option -XM/--max-input: $uq_max_input_human_readable_size"
 
 argc=${#argv[@]}
 
@@ -229,6 +261,13 @@ BEGIN {
 }
 
 {
+    total_input_size += length + 1
+    if (total_input_size > uq_max_input_size) {
+        printf "[%s] ERROR: input size exceed max input size %s!\nuse option -XM/--max-input specify a REASONABLE larger value.\n",
+            uq_PROG, uq_max_input_human_readable_size > "/dev/stderr"
+        exit(1)
+    }
+
     # use index to keep lines order
     original_lines[line_index++] = $0
 
@@ -255,6 +294,9 @@ awk \
     -v "uq_opt_only_unique=$uq_opt_only_unique" \
     -v "IGNORECASE=$uq_opt_ignore_case" \
     -v "uq_opt_zero_terminated=$uq_opt_zero_terminated" \
+    -v "uq_max_input_human_readable_size=$uq_max_input_human_readable_size" \
+    -v "uq_max_input_size=$uq_max_input_size" \
+    -v "uq_PROG=$PROG" \
     -f <(printf "%s" "$uq_awk_script") \
     -- ${input_files[@]:+"${input_files[@]}"} \
     >"$output_file"
